CREATE TABLE IF NOT EXISTS list(
  id UUID PRIMARY KEY,
  title VARCHAR NOT NULL,
  description VARCHAR NOT NULL,
  priority SMALLINT,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
)