CREATE TABLE IF NOT EXISTS tab(
  id UUID PRIMARY KEY,
  title VARCHAR(15) NOT NULL,
  layout JSON,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);
ALTER TABLE IF EXISTS task
ADD COLUMN tab_id UUID REFERENCES tab(id);