// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNewItem = `-- name: CreateNewItem :one
INSERT INTO list(
    id,
    title,
    description,
    priority,
    created_at,
    updated_at
  )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateNewItemParams struct {
	ID          uuid.UUID   `json:"id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Priority    pgtype.Text `json:"priority"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

func (q *Queries) CreateNewItem(ctx context.Context, arg CreateNewItemParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createNewItem,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAllItems = `-- name: GetAllItems :many
SELECT id, title, description, priority, created_at, updated_at
from list
`

func (q *Queries) GetAllItems(ctx context.Context) ([]List, error) {
	rows, err := q.db.Query(ctx, getAllItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []List
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItem = `-- name: GetItem :one
SELECT id, title, description, priority, created_at, updated_at
from list
WHERE id = $1
`

func (q *Queries) GetItem(ctx context.Context, id uuid.UUID) (List, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateItem = `-- name: UpdateItem :exec
UPDATE list
SET title = $2,
  description = $3,
  priority = $4,
  updated_at = $5
WHERE id = $1
`

type UpdateItemParams struct {
	ID          uuid.UUID   `json:"id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Priority    pgtype.Text `json:"priority"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) error {
	_, err := q.db.Exec(ctx, updateItem,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.UpdatedAt,
	)
	return err
}
