// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tab.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createNewTab = `-- name: CreateNewTab :one
INSERT INTO tab(
    id,
    title,
    layout,
    created_at,
    updated_at
  )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, layout, created_at, updated_at
`

type CreateNewTabParams struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	Layout    []byte    `json:"layout"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateNewTab(ctx context.Context, arg CreateNewTabParams) (Tab, error) {
	row := q.db.QueryRow(ctx, createNewTab,
		arg.ID,
		arg.Title,
		arg.Layout,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Tab
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Layout,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllTabs = `-- name: GetAllTabs :many
SELECT id, title, layout, created_at, updated_at
FROM tab
`

func (q *Queries) GetAllTabs(ctx context.Context) ([]Tab, error) {
	rows, err := q.db.Query(ctx, getAllTabs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tab
	for rows.Next() {
		var i Tab
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Layout,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTab = `-- name: GetTab :one
SELECT id, title, layout, created_at, updated_at
FROM tab
where id = $1
`

func (q *Queries) GetTab(ctx context.Context, id uuid.UUID) (Tab, error) {
	row := q.db.QueryRow(ctx, getTab, id)
	var i Tab
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Layout,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTab = `-- name: UpdateTab :exec
UPDATE tab
SET title = COALESCE($2, title),
  layout = COALESCE($3, layout),
  updated_at = $4
WHERE id = $1
`

type UpdateTabParams struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	Layout    []byte    `json:"layout"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateTab(ctx context.Context, arg UpdateTabParams) error {
	_, err := q.db.Exec(ctx, updateTab,
		arg.ID,
		arg.Title,
		arg.Layout,
		arg.UpdatedAt,
	)
	return err
}
